apiVersion: v1
baseDomain: mylab.local
metadata:
  name: cls-dev-01

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

proxy:
  httpProxy: http://172.17.170.68:443
  httpsProxy: http://172.17.170.68:443
  noProxy: >-
    .cimbniaga.co.id,
    .mylab.local
    .svc,
    .cluster.local,
    127.0.0.1,
    localhost,
    10.128.0.0/14,
    172.30.0.0/16,
    192.168.122.0/24,
    api.cls-dev-01.mylab.local,
    api-int.cls-dev-01.mylab.local,
    image-registry.openshift-image-registry.svc:5000

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}' 
sshKey: 'ssh-ed25519 AAAA...'   
